#tova e promenlivata "packages"
packages: 
- "net-tools"
- "gnome-tweaks"
- "ifupdown"
- "guake"
- "htop"
- "snap"
- "openjdk-8"
- "openjdk-8-jre-headless"
- "openjdk-11-jre-headless"
- "openjdk-13-jre-headless"
- "openjdk-14-jre-headless"
- "discord"
- "messengerport"
- "git"
- "icedtea-netx"
- "winetricks"
- "chromium-browser"
- "unrar"
- "guake"